//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaMotors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public int InventoryId { get; set; }
        public string FilePath { get; set; }
        public byte[] MainPhoto { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
